global:
  scrape_interval: 15s  # Tiempo entre cada recolección de métricas

scrape_configs:
  - job_name: 'mongodb'
    static_configs:
     - targets: ['mongo-exporter:9216']

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
