name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # O la rama que uses para producción
    paths:
      - '**/docker-compose.yml'  # Si usas Docker Compose

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build -t my-app:${{ github.sha }} .
    
    - name: Push Docker image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        docker tag my-app:${{ github.sha }} mariavillalba/my-app:${{ github.sha }}
        docker push mariavillalba/my-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to production
      run: |
        ssh user@your-server-ip 'docker pull mariavillalba/my-app:${{ github.sha }} && docker run -d mariavillalba/my-app:${{ github.sha }}'